version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
    image: budget-buddy-backend
    container_name: budget-buddy-backend
    volumes:
      - ../:/home/workspace
      - /home/workspace/node_modules
      - /home/workspace/.pnpm-store
    ports:
      - 4000:3000
    environment:
      NODE_ENV: production
    entrypoint: bash
    stdin_open: true
    tty: true